foxygoat/s

- .github/workflows/ci.yaml
- .github/workflows/version.yaml
- .gitignore
- .golangci.yaml
- LICENSE
- Makefile
- README.md
- errs/errs.go
- errs/errs_test.go
- go.mod
- go.sum
Create package `errs` which exports `New` and `Errorf` functions, both
allowing to wrap more than a single error. The newly created error is
query-able with `errors.Is` and `errors.As`.
This extension is particularly useful when tagging an error with  a
sentinel error value _and_ keeping the underlying, causing error.
Create Makefile for test, lint and coverage. Configure golangci-lint in
.golangci.yaml and add coverage.out to .gitignore.
Create basic GitHub action for CI.
It seems that pulling golangci-lint is the slow piece of this build :(.
I've tried using https://github.com/actions-contrib/golangci-lint - but got some version conflicts.
Add README.md, linter config .golangci.yaml, .gitignore.
> Set up build infrastructure and errs package

- .golangci.yaml
- httpe/example_httpe_test.go
- httpe/httpe.go
- httpe/httpe_test.go
- mock/responsewriter.go
Implement core functionality of httpe package: an http.Handler that can
return an error.
type HandlerE interface {
ServeHTTP(http.ResponseWriter, *http.Request) error
}
It is intended to be used with ErrWriter which handles the error and
turns it into an appropriate http response StatusCode and Body.
type ErrWriter interface {
Write(http.ResponseWriter, error)
}
`Chain` chains several `HandlerE`s sequentially and bails on the first
error.
`NewHandler` creates a traditional `http.Handler` from a `HandlerE` and
`ErrWriter` and `NewHandlerFunc` creates an `http.HandlerFunc` from
`HandlerFuncE` and `ErrWriterFunc`.
The httpe package also provides HandlerFuncE and ErrWriterFunc types as
adapters to the interfaces, similar to http.HandlerFunc for http.Handler
interface.
Introduce new `mock` …
> Initialise httpe package

- README.md
Link directly to #foxygoat channel on gophers Slack workspace for
discussion.
> docs: Add Slack badge to README.md

- go.mod
- go.sum
- timex/example_timex_test.go
- timex/timex.go
- timex/timex_test.go
Create package timex with type Ticker. A Ticker that holds a channel
that delivers 'ticks' of a clock at intervals, similar to time.Ticker
from the standard library.
It differs from the standard library Ticker by closing C when
Stop() is called, which allows for ranging over C:
for range ticker.C {
// do something
}
Add creation functions:
- `NewTicker(d time.Duration)` 
- `NewTickerWithContext(d time.Duration)` 
`NewTickerWithContext` stops when the context gets cancelled.
> Create timex package

- Makefile
lint-with-docker is a PHONY target, but we've missed listing it as such.
Fix it.
> build: Add missing PHONY prerequisites

- timex/example_timex_test.go
- timex/timex_test.go
Improve flaky test by increasing the time slices we work with for
single to double digit milli seconds.
Let's hope Cam isn't right _again_.
> Improve flaky timex test

- str/camel.go
- str/camel_test.go
Add `ToCamelCase` to convert a string to lower camel case for
identifiers, making the first word of the identifier lowercase.
Rename the file `str.go` to `camel.go` since it is becoming about camel
case functions. Rename `str_test.go` to `camel_test.go` as appropriate.
> str: Add ToCamelCase function

- Makefile
- cmd/retry/retry.go
- cmd/timeout/timeout.go
Add a couple of small snippet commands for chaining on the command line to
run commands with a timeout and to retry commands if they fail.
They chain to timeout and retry a dodgy command:
retry 2 timeout 5s dodgy-command args
Update the Makefile with a build section.
Update the Makefile to use the latest form we have settled on, with an
`out/` directory for generated output and style changes to section markers.
> cmds: Add retry and timeout commands

- .gitignore
- Makefile
- cmd/timeout/test.sh
- cmd/timeout/timeout.go
The original version of `timeout` used a context with a timeout to have
`exec.Cmd` kill the running command. However, that uses `SIGKILL` which
does not give the child process a chance to clean up. In the case where
this was used, `gcloud` had forked a child process. When the parent was
killed with `SIGKILL` it was not able to clean up the child.
Now `SIGTERM` is sent and if the process has not exited within a given
grace period (3s by default), then it is killed with `SIGKILL`. The signal
and grace period can be set with `-s` and `-g` respectively.
Also, fix up `.gitignore` while we're here.
> timeout: Don't kill with SIGKILL on timeout

- test/doc.go
- test/env.go
- test/env_test.go
Add some helpers for setting up the OS environment in tests and
restoring it after the test is done.
A type `test.Environ` is added that can set and unset the OS
environment, keeping a record of what changes it makes. At the end of a
test, the `Restore()` method can be called to return the environment
back to the starting state.
A global variable `test.Env` is provided for simplicity as the OS
environment itself is global, it is not usually necessary to instantiate
the `test.Environ` struct.
> test: Add some environment test helpers

- .github/dependabot.yaml
Create dependabot.yaml for a basic set up to automatically check daily on go.mod dependencies.
Follow documentation at
https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
> Setup dependabot

- test/env.go
- test/env_test.go
The global Env map was not initialised/made. This causes a panic when
trying to use it as documented. Add an intitialiser for it.
> test: Initialise global Env map

- .github/dependabot.yaml
- Run dependabot monthly instead of daily.
- Change commit prefix from 'build(deps)' to 'deps'.
> github: Tweak dependabot setup

- .github/workflows/version.yaml
When bumping the version of the module (creating the tag), use `go get`
to pull the version via the standard Go proxy so that the docs at
pkg.go.dev get updated.
> ci: Update pkg.go.dev on version bump

- .github/workflows/version.yaml
The previous commit added a step to the version bump to `go get` @latest
of the Go module so it will appear in the docs at pkg.go.dev. But it
seemed to get the old version with @latest, so use the tag just set
explicitly and see if that works, of if there is a race condition with
github setting the tag and fetching the latest tag.
> ci: Fix pkg.go.dev tag pull

- httpe/example_httpe_test.go
- httpe/httpe.go
- httpe/httpe_test.go
Use the options pattern to unify `NewHandler` and `NewSafeHandler` (and
their `Func` siblings) so that the default is now to use `WriteSafeErr`
to write errors to the `http.ResponseWriter` and allow it to be
overridden with an option `WithErrWriter`/`WithErrWriterFunc`.
The make simple use simple, keeping a tighter but extensible API
surface.
Link: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis
Link: https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html
> httpe: Unify NewHandler/NewSafeHandler with options

- httpe/example_new_test.go
- httpe/httpe.go
- httpe/httpe_test.go
Add a `New()` function that accepts various types of parameters
representing handlers and chain them together calling them one after the
other. Each is treated as a HandlerE so can return errors. If any
handler in the chain does return an error, no further handlers in the
chain are called, and the error is passed to an ErrWriter.
One ErrWriter can be supplied in the argument list (anywhere), and that
will be used as the ErrWriter to handle errors. If none is supplied,
then the default `WriteSafeErr` is used.
The types of handlers accepted are HandlerE and http.Handler (which
includes http.HandlerFunc and HandlerFuncE), and also plain functions
that match the HandlerFunc types. Same for the ErrWriter arg - it can be
a function that matches ErrWriterFunc.
This dynamic typing makes the use …
> httpe: Add New() function for magical chaining

- .github/workflows/version.yaml
Automate release generation on every merge to master after auto-tagging.
This makes the most recent release more prominent on the repo frontpage
and allows for downloading a tarball.
> Automate release generation

- cmd/retry/retry.go
- cmd/timeout/timeout.go
Add some godocs to the two commands, retry and timeout, so they are not
blank in the godocs. Now I'll remember how to use them.
> cmd: Add godocs for commands

- errs/ignore.go
- errs/ignore_test.go
Add Ignore error function to be used with defer. Ignore executes nullary
input function f and ignores its error return value. A typical use case
is ignoring errors in the defer statements:
defer errs.Ignore(body.Close)
> errs: Add Ignore function

- test/json.go
- test/json_test.go
- test/testdata/invalid.json
- test/testdata/profile.json
Add ReadJSON from file test utility function that fails the test
immediately if the file cannot be read or parsed into the provided data
structure.
cfg := Config{}
test.ReadJSON(t, "testdata/config.json", &cfg)
> Add ReadJSON from file test utility

- .github/workflows/ci.yaml
- .github/workflows/version.yaml
Change the version of the setup-go action to v2 from v2.1.2. Later
versions fix problems and we want those fixes automatically. In this
case, GitHub has disables the `set-env` and `add-path` commands which
v2.1.2 used. We need a newer version. Rather than bumping to a new point
release, just use "v2". (my personal preference is for reproducible
builds, so we used a specific version, but that is not really necessary
as we can reproduce a build manually).
> github: Unpin setup-go version, just use "v2"
